# -*- coding: utf-8 -*-
"""aula2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q__kLCTf_9GPSoUpUNcA0Mmbuv7lC-pJ
"""

#Introdução as listas

cidades =['São Paulo','Guarulhos','Rio de Janeiro']
#print(cidades[1])

for cidade in cidades:
  print(cidade)

#Introdução ao while

botaoExecutar = True
contador = 0
while botaoExecutar:
  print(contador)
  contador = contador + 1
  if contador >= 10:
    botaoExecutar = False

#Introdução a funções

def minhaFuncao():
  print('Minha função')

minhaFuncao()

cidades =['São Paulo','Guarulhos','Rio de Janeiro']
contador = 0

def funcao(informacao, x):
  print(str(x) + ' - ' + informacao)

for cidade in cidades:
  contador = contador + 1
  funcao(cidade, contador)

#Projeto calculadora

executar = True

while executar:
  escolhas = '''
  Operações de calculo permitidas
  [1] ou [+] - Soma
  [2] ou [/] - Divisão
  [3] ou [*] - Multiplicação
  [4] ou [-] - Subtração
  [5] ou [**] - Potencia
  [0] ou [Sair] - Sair
  '''

  print(escolhas)
  operador = input('Selecione sua opção')
  if operador == '0' or operador == 'Sair':
    print('Obrigado por utilizar a calculadora!')
    executar = False
  else:
    valor01 = input('Escolha seu primeiro valor')
    valor02 = input('Escolha seu segundo valor')

    valor01 = int(valor01)
    valor02 = int(valor02)

    if operador == '1' or operador == '+':
      resultado = valor01 + valor02
      print('O resultado é: ' + str(resultado))

    if operador == '2' or operador == '/':
      resultado = valor01 / valor02
      print('O resultado é: ' + str(resultado))
    
    if operador == '3' or operador == '*':
      resultado = valor01 * valor02
      print('O resultado é: ' + str(resultado))
  
    if operador == '4' or operador == '-':
      resultado = valor01 - valor02
      print('O resultado é: ' + str(resultado))
    
    if operador == '5' or operador == '**':
      resultado = valor01 ** valor02
      print('O resultado é: ' + str(resultado))

#Criando um programa que pergunta o ano de nascimento, em qual ano estamos, e descobre a idade do usuário

anoAtual = int(input('Digite em que ano estamos: '))
executar = True

while executar:
  anoNascimento = int(input('Digite o seu ano de nascimento: '))
  idade = anoAtual - anoNascimento
  print('\nA sua idade é igual a ' + str(idade))
  opcao = input('\nDeseja tentar novamente? \n[1] Sim [2] Não ')
  if opcao == '1':
    executar = True
  if opcao == '2':
    print('\nVolte sempre')
    executar = False