# -*- coding: utf-8 -*-
"""aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AuaLNqInN1qHTDvfTf5A-3gUfnbhqkzc
"""

print('Hello World')

#Isso é um comentário com quebra de linha (\n)
print('Meu nome é Eduardo.\nEstou fazendo o curso de Python.')

nome = 'Eduardo'
sobrenome = 'Graciano'
idade = 24
altura = 1.72
celular = "972896883"
nomeCompleto = nome + ' ' + sobrenome

print(nome + ' ' + sobrenome)

#Exibindo um int como string
print(nomeCompleto + ' tem ' + str(idade) + ' anos')

#Descobrindo o tipo de uma variável
print(type(idade))

#Transformando o tipo de uma variável
idade = str(idade)
print(type(idade))

#Criando inputs e alterando o seu tipo (que inicialmente é sempre string)
valor1 = int(input('Insira o primeiro valor: '))
valor2 = int(input('Insira o segundo valor: '))

print(type(valor1))

#Introdução às estruturas condicionais

mediaAluno = float(input('Digite a nota do aluno: '))

if mediaAluno >= 7 :
  print('Você foi aprovado')
else:
  print('Você foi reprovado')

mediaAluno = float(input('Digite a nota do aluno: '))
freqAluno = float(input('Digite a frequência do aluno: '))

if mediaAluno >= 7 and freqAluno >= 70:
  print('Você foi aprovado')
else:
  print('Você foi reprovado')

#Testando condicionais com o cáçculo de IMC

altura = float(input('Digite a altura do usuário: '))
peso = float(input('Digite o peso do usuário: '))

imc = peso / (altura * altura)
#print('O IMC do usuário é igual a ' + str(imc))
print(f'O IMC do usuário é igual a {imc:0.2f}')

if imc < 18.5:
  print('O usuário está abaixo do peso ideal')
elif imc >= 18.5 and imc <= 24.99:
  print('O usuário está com o peso normal')
elif imc >= 25 and imc <= 29.99:
  print('O usuário está com sobrepeso')
elif imc >= 30:
  print ('o usuário está obeso')

#Iniciando as estruturas de repetição com for

nome = 'Eduardo'
for letra in nome:
  print(letra)